# Generated by Django 5.2.5 on 2025-08-20 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('foto', models.ImageField(upload_to='absensi_foto/')),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu Verifikasi'), ('hadir', 'Hadir'), ('izin', 'Izin'), ('alpha', 'Alpha')], default='menunggu', max_length=20)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absensi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
